### ISSUE TITLE
console.log value assigned to temporary parameter

### ISSUE THREAD

**Issue by sivaprabug** [chrisvltn/vs-code-log-wrapper#1]
Hi,

Can you modify the console.log('name',name); to  console.log('name',**nameVal = name**); like that its easy to debug for developers.

We can access the ***nameVal*** in console for calling and binding is easy.

![github](https://cloud.githubusercontent.com/assets/2444608/23364446/1f56d248-fd25-11e6-8bff-4167c672d4e1.jpg)

regards,

@gsivaprabu

**Comment by chrisvltn** [comment]
This can be done in your settings, by setting a custom debug wrapper.

Go to your settings in VS Code and set the following option:

```json
"debugwrapper.wrappers": {
    "javascript": "console.log(`$eSEL`, $SELVal = $SEL);"
}
```

`$SEL` will be replaced by the selection, so you can reach your approach easily :smile: 

Thank you for contributing!
