### ISSUE TITLE
How to add die after wrapper log

### ISSUE THREAD

**Issue by hoangnamitc** [chrisvltn/vs-code-log-wrapper#3]
Hi !

Please support me How to add "die" after wrapper log.

tks!

**Comment by chrisvltn** [comment]
Hi!
You can use the same approach we used in issue #1 

Go to your VS Code settings and set the following option: 

```json
"debugwrapper.wrappers": {
    "javascript": "console.log(`$eSEL`, $SEL); die"
}
```

Change `javascript` for the language that you are using :)

Thank you for contributing!
Solved and closed

**Comment by hoangnamitc** [comment]
Thanks !
