### ISSUE TITLE
console.log value assigned to temporary parameter

### ISSUE THREAD

**Issue by sivaprabug** [chrisvltn/vs-code-log-wrapper#4]
Hi,

Can you modify the console.log('name',name); to console.log('name',nameVal = name); like that its easy to debug for developers.

We can access the nameVal in console for calling and binding is easy.

![image](https://user-images.githubusercontent.com/2444608/48407199-45de3c80-e75c-11e8-9869-64801f57d30e.png)

Refer Sublime plugin:-

https://github.com/unknownuser88/consolewrap/issues/10

regards,

@gsivaprabu

**Comment by chrisvltn** [comment]
This can be done in your settings, by setting a custom debug wrapper.

Go to your settings in VS Code and set the following option:

```json
"debugwrapper.wrappers": {
    "javascript": "console.log(`$eSEL`, $SELVal = $SEL);"
}
```

`$SEL` will be replaced by the selection, so you can reach your approach easily :smile: 

Thank you for contributing!

**Comment by sivaprabug** [comment]
Thanks @chrisvltn  for your valuable reply. If i add separate shortcut key for temp feature means i can able in vscode settings.json itself possible ?
